apiVersion: v1
kind: Service
metadata:
  name: nginx-service
spec:
  type: NodePort
  selector:
    app: nginx
  ports:
  - name: name-of-service-port
    protocol: TCP
    port: 80
    nodePort: 31002
    # target port 沒有給的時候它會設定為 `port` 的值
    # apply pod containerport 可以給訂名稱，這邊就可以給名稱
    # targetPort: http-web-svc
    targetPort: 8080

