apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment
  labels:
    app: nginx
spec:
  replicas: 3
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: nginx
        image: nginx:1.26.2
        ports:
        - containerPort: 8080
          name: http-web-svc
        volumeMounts:
        - name: nginx-conf
          mountPath: /etc/nginx/conf.d
          readOnly: true
        env:
        - name: SECRET_USERNAME
          valueFrom:
            secretKeyRef:
              name: nginx-secret
              key: backend-username
      volumes:
      - name: nginx-conf
        configMap:
          # 參考 configmap 名稱
          name: nginx-conf
          items:
          # config map 當中的 key
          - key: default.conf
          # 要建立的檔案名稱
            path: default.conf
